# @name generic
GET https://services5.arcgis.com/mnYJ21GiFTR97WFg/arcgis/rest/services/slide_fig/FeatureServer/0/query
?f=json&where=1%3D1&returnGeometry=false&spatialRel=esriSpatialRelIntersects&outFields=*&outStatistics=%5B%7B%22statisticType%22%3A%22sum%22%2C%22onStatisticField%22%3A%22tests%22%2C%22outStatisticFieldName%22%3A%22value%22%7D%5D&cacheHint=true


###

# @name medicalFacility
https://services5.arcgis.com/mnYJ21GiFTR97WFg/arcgis/rest/services/PH_masterlist/FeatureServer/0/query
?f=json
&where=1%3D1
&returnGeometry=false
&spatialRel=esriSpatialRelIntersects
&outFields=*
&orderByFields=value desc
&resultOffset=0
&resultRecordCount=1000
&cacheHint=true
&groupByFieldsForStatistics=facility
&outStatistics=[{"statisticType":"count","onStatisticField":"FID","outStatisticFieldName":"value"}]
###

# @name city
GET https://services5.arcgis.com/mnYJ21GiFTR97WFg/arcgis/rest/services/PH_masterlist/FeatureServer/0/query?f=json&where=1%3D1&returnGeometry=false&spatialRel=esriSpatialRelIntersects&outFields=*&groupByFieldsForStatistics=residence&orderByFields=value%20desc&outStatistics=%5B%7B%22statisticType%22%3A%22count%22%2C%22onStatisticField%22%3A%22FID%22%2C%22outStatisticFieldName%22%3A%22value%22%7D%5D&cacheHint=true
###

# @name country
GET https://services.arcgis.com/5T5nSi527N4F7luB/arcgis/rest/services/Cases_by_country_pt_V3/FeatureServer/0/query?
f=json&where=1%3D1&returnGeometry=true&spatialRel=esriSpatialRelIntersects&maxAllowableOffset=78271&geometry=%7B%22xmin%22%3A-20037508.342788905%2C%22ymin%22%3A-20037508.342779063%2C%22xmax%22%3A20037508.342779063%2C%22ymax%22%3A20037508.342788905%2C%22spatialReference%22%3A%7B%22wkid%22%3A102100%7D%7D&geometryType=esriGeometryEnvelope&inSR=102100&outFields=*&outSR=102100&resultType=tile


###

# @name groupedByGender
GET {{baseUri}}/mnYJ21GiFTR97WFg/arcgis/rest/services/PH_masterlist/FeatureServer/0/query
?f=json
&where=1%3D1
&returnGeometry=false
&spatialRel=esriSpatialRelIntersects
&outFields=*
&resultOffset=0
&resultRecordCount=1000
&cacheHint=true
&orderByFields=value asc
&groupByFieldsForStatistics=nationalit 
&outStatistics=[{"statisticType":"count","onStatisticField":"FID","outStatisticFieldName":"value"}]
###


###

# @name groupedByGender
GET {{baseUri}}/mnYJ21GiFTR97WFg/arcgis/rest/services/age_group/FeatureServer/0/query
?f=json
&where=1%3D1
&returnGeometry=false
&spatialRel=esriSpatialRelIntersects
&outFields=*
&orderByFields=age_categ asc
&resultOffset=0
&resultRecordCount=1000
&cacheHint=true
&groupByFieldsForStatistics=age_categ,sex
&outStatistics=[{"statisticType":"count","onStatisticField":"FID","outStatisticFieldName":"value"}]
###


# @name groupedByConfirmed
GET {{baseUri}}/mnYJ21GiFTR97WFg/arcgis/rest/services/confirmed/FeatureServer/0/query
?f=json
&where=1%3D1
&returnGeometry=false
&spatialRel=esriSpatialRelIntersects
&outFields=*
&orderByFields=date asc
&resultOffset=0
&resultRecordCount=1000
&cacheHint=true
&groupByFieldsForStatistics=date
&outStatistics=
###

# @name groupedByOF

GET {{baseUri}}/mnYJ21GiFTR97WFg/arcgis/rest/services/slide_fig/FeatureServer/0/query
?f=json
&where=1%3D1
&returnGeometry=false
&spatialRel=esriSpatialRelIntersects
&outFields=*
&orderByFields=
&resultOffset=0
&resultRecordCount=1000
&cacheHint=true
&outStatistics=
###



# @name inventory

GET {{baseUri}}/mnYJ21GiFTR97WFg/arcgis/rest/services/commodities/FeatureServer/0/query
?f=json
&where=1%3D1
&returnGeometry=false
&spatialRel=esriSpatialRelIntersects
&outFields=*
&orderByFields=
&cacheHint=true
&outStatistics=
###


# @name PUIRegion

GET {{baseUri}}/mnYJ21GiFTR97WFg/arcgis/rest/services/PUI_fac_tracing/FeatureServer/0/query
?f=json
&where=1%3D1
&returnGeometry=false
&spatialRel=esriSpatialRelIntersects
&outFields=*
&orderByFields=value desc
&cacheHint=true
&groupByFieldsForStatistics=hf
&outStatistics=[{"statisticType":"sum","onStatisticField":"PUIs","outStatisticFieldName":"value"}]
###